apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: sjh-app1
spec:
  selector:
    matchLabels:
      app: sjh-app1
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: sjh-app1
    spec:
      containers:
      - name: sjh-app1
        image: shussey/app-in-docker
        ports:
        - containerPort: 8080
