apiVersion: v1
kind: Service

metadata:
  name: sjh-app1-service
spec:
  type: NodePort
  selector:
    app: sjh-app1
  ports:
    - protocol: TCP
      nodePort: 31364
      port: 80
      targetPort: 8080